// types ...
const FETCH_WEATHER_START = 'FETCH_WEATHER_START';
const FETCH_WEATHER_SUCCES = 'FETCH_WEATHER_SUCCES';
const FETCH_WEATHER_FAIL = 'FETCH_WEATHER_FAIL';
const ADD_CITY_TO_LIST = 'ADD_CITY_TO_LIST';
const SET_CURRENT_CITY = 'SET_CURRENT_CITY';

export default {
  FETCH_WEATHER_START,
  FETCH_WEATHER_SUCCES,
  FETCH_WEATHER_FAIL,
  ADD_CITY_TO_LIST,
  SET_CURRENT_CITY,
};
