// types ...
const FETCH_WEATHER_START = 'FETCH_WEATHER_START';
const FETCH_WEATHER_SUCCES = 'FETCH_WEATHER_SUCCES';
const FETCH_WEATHER_FAIL = 'FETCH_WEATHER_FAIL';

export default {
  FETCH_WEATHER_START,
  FETCH_WEATHER_SUCCES,
  FETCH_WEATHER_FAIL,
};
